# Generated by Django 3.2.18 on 2023-04-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='country',
            field=models.CharField(default='Việt Nam', max_length=255, verbose_name='Quốc gia'),
        ),
    ]
