# Generated by Django 3.2.18 on 2023-04-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='abc',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tiêu đề'),
        ),
    ]
