# Generated by Django 3.2.18 on 2023-04-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_videopost_abc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='abc',
        ),
    ]
