# Generated by Django 3.2.18 on 2023-04-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_remove_videopost_abc'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleniumcrawlerconfig',
            name='google_credential',
            field=models.FileField(default='', upload_to='', verbose_name='Google Credential'),
            preserve_default=False,
        ),
    ]
