# Generated by Django 3.2.18 on 2023-04-24 13:57

import crawler.models
import crawler.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_seleniumcrawlerconfig_google_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleniumcrawlerconfig',
            name='google_credential',
            field=models.FileField(max_length=255, storage=crawler.storage.OverwriteStorage(), upload_to=crawler.models.image_path, verbose_name='Google Credential'),
        ),
    ]
